- lib/mapping/ep_identifier_to_wikidata.rb
- lib/membership_list/morph.rb
- lib/membership_list/wikidata.rb
- prompt_prototype.rb
This pull request hopefully separates out the code that (a) goes to remote services (such as a Morph scraper, the Wikidata SPARQL endpoint and EveryPolitician) to generate lists of memberships and ID mappings from (b) the code left in in the `prompt_prototype.rb` script, which takes those and produces a list of discrepancies between the sources.
Hopefully this makes it easier to look at the `prompt_prototype.rb` script to work out what might be the next functionality that could be factored out.
The `MembershipLists` classes return an array of one hash via their `to_a` method, where each hash has properties of a particular membership.
n.b. I haven't added automated tests for this because before doing extra work to do that, I'd quite like feedback on whether this generally looks like a …
> Extract into classes code for fetching membership lists and ID mappings

- exe/prompt
- lib/compare_with_wikidata/membership_list/wikidata.rb
Trying to generate a SPARQL query that's general enough to encapsulate
all the possible ways things might have been modelled it tricky, if not
impossible. So for the time being just push this problem out of band and
force the user to provide their own SPARQL query.
> Make SPARQL query a parameter rather than generating it

- exe/compare_with_wikidata
- templates/mediawiki.erb
Rather than printing the output immediately we use a template so that we
can gather up the output and send it somewhere else.
This allows us to potentially redirect the output somewhere other than
STDOUT, e.g. the MediaWiki API.
> Move MediaWiki generation into template

- compare_with_wikidata.gemspec
- exe/compare_with_wikidata
- templates/mediawiki.erb
This uses the [mediawiki-page-replaceable_content](https://github.com/everypolitician/mediawiki-page-replaceable_content) library to interact with Wikidata directly.
Fixes #18 
Please complete the following before merging:
> Integrate with wikidata

- exe/compare_with_wikidata
- lib/compare_with_wikidata.rb
- lib/compare_with_wikidata/diff_row.rb
- templates/mediawiki.erb
This adds some extra template parameters which can be used to specify custom templates to be used when rendering a prompt page.
You can see custom templates in action [on this Heads of Government report](https://www.wikidata.org/w/index.php?title=User:Chris_Mytton/sandbox/daff_heads_of_government&oldid=531283823), where I've used them to hide the additions and removals so it only shows the modifications.
Fixes #16 
Please complete the following before merging:
> Allow user to supply templates

- lib/compare_with_wikidata/diff_row.rb
- lib/compare_with_wikidata/diff_row/cell.rb
This adds additional template parameters that are passed to the custom row templates. If there's a `holder_id` parameter we now also pass in `holder_id_sparql` and `holder_id_wikidata` so that the template creator can inspect those values and act accordingly.
Fixes #51
> Separate template parameters for SPARQL and CSV values

- lib/compare_with_wikidata.rb
If the schema of the SPARQL query is different to the CSV then raise an
error telling the user about the problem.
Fixes #59
> Detect differing schema and raise error

- lib/compare_with_wikidata.rb
- lib/compare_with_wikidata/membership_list/wikidata.rb
Rather than requiring the SPARQL and CSV to return exactly the same headers we simply check for common headers between the two sources and diff those.
Fixes #69
> Use common headers from SPARQL and CSV

- compare_with_wikidata.gemspec
- lib/compare_with_wikidata.rb
- test/compare_with_wikidata_test.rb
- test/test_helper.rb
If you accidentally supply a URL for something that isn't a valid CSV
file in the subpage that should have a URL for a CSV file, then the
error you get from the prompter tool is confusing - you'll just see
something like:
"Error: Illegal quoting in line 8."
... with no hint about where that line is. The change introduced by this
commit catches malformed CSV errors and re-raise a new exception with a
more friendly message - something like:
"The URL http://example.com/invalid.csv couldn't be parsed as CSV. Is it really a valid CSV file?"
Fixes #62
> Catch malformed CSV errors to provide a more helpful error message

- lib/compare_with_wikidata.rb
- lib/compare_with_wikidata/comparison.rb
- templates/comparison.erb
- templates/header_template.erb
- templates/row_added.erb
- templates/row_modified.erb
- templates/row_removed.erb
- templates/stats.erb
- test/compare_with_wikidata/comparison_test.rb
This moves the code for interacting with daff into a `Comparison` class. I've also added some (_very_ basic) tests for this new class.
This refactoring was prompted by wanting to add a regression test when fixing #65. Because the code I wanted to add a regression test for was [deep in `CompareWithWikidata::DiffOutputGenerator#run!`](https://github.com/everypolitician/compare_with_wikidata/blob/master/lib/compare_with_wikidata.rb#L41-L43) adding a test would have meant writing a full end to end integration test. So this pull request is in the spirit of "make the change easy and then make the easy change".
Should unblock #65
> Move daff logic into separate class and add tests

- lib/compare_with_wikidata.rb
This change catches any error which is a subclass of StandardError, and
stores it in a `/errors` subpage. If there was no error, it deletes all
content from the `/errors` subpage. This means that we can update the
"Compare Wikidata with CSV" template to display these errors in-page,
for example like:
Part of the fix for #66
> Make a /errors subpage reflect whether the last run errored

- lib/compare_with_wikidata/comparison.rb
- test/compare_with_wikidata/comparison_test.rb
We want to remove any URL prefixes that are returned from the SPARQL query before running the comparison. This means the CSV file only needs to include Wikidata IDs, rather than full URLs.
The `cleaned_cell` method doesn't feel _quite_ right, but I think introducing a whole new `Cell` (or whatever) class just to strip the URL prefix seemed like a bit of an overkill. I'm open to any alternative suggestions though!
Fixes #65
> Remove Wikidata URL prefix before diffing

- lib/compare_with_wikidata/comparison.rb
If there are columns that contain no changes then we still want those to be returned by daff.
Without this flag daff replaces the unchanged column(s) with three dots (...), which leads to confusing prompt output.
Fixes #82
> Output unchanged columns from daff

- lib/compare_with_wikidata.rb
- lib/compare_with_wikidata/diff_row.rb
- templates/comparison.erb
- templates/stats.erb
Write the default templates out _every time_ the prompt is refreshed. Then check for a custom template and if it's missing or empty then fallback to the default template.
This means that adding or removing columns will be reflected in the default templates. It also keeps the existing behaviour of blanking a template to go back to the default, but is now doing this check in Wikidata, rather than in Ruby.
The only drawback to this approach is that the "edit the header template" type links will be red initially, so the user won't be able to simply edit the default. I think we can possibly remedy that by having an **Install default templates** button which copies the default templates into the custom paths.
Fixes #73
> Split up default and custom templates

- templates/comparison.erb
- templates/stats.erb
We were previously checking if the default templates returned any contents using `#if`, but that doesn't handle templates that don't exist, because they do actually return contents: a red link to create the missing page.
This change adds an extra `#ifexist` check to ensure the template exists before we render it.
Fixes #87
> Check that custom templates exist before rendering

- templates/comparison.erb
Use the full template name, rather than a "relative" (in MediaWiki terms) path, so that the `/comparison` subpage of the prompt can be viewed by visiting that page.
This means that when people are watching the page they can just view the changes on their own. It also means you can go back through the history of the comparison page and view older versions of it.
You can see this in action on [User:Chris_Mytton/sandbox/prompts/Riigikogu/comparison](https://www.wikidata.org/w/index.php?title=User:Chris_Mytton/sandbox/prompts/Riigikogu/comparison&oldid=552199241).
Fixes #89
> Make comparison page viewable directly

- lib/compare_with_wikidata/diff_row.rb
- test/compare_with_wikidata/diff_row_test.rb
We want to replace values like "Q42" with the full template tag, like "{{Q|42}}", however this was being a bit over-eager and replacing things that weren't actually Wikidata IDs.
To avoid this problem I've changed the regex so that it only matches a Q value if it is the entire contents of the cell.
Fixes #92
> Only match Q values if they span the whole cell

- lib/compare_with_wikidata.rb
- test/compare_with_wikidata/diff_output_generator_test.rb
At the moment, when the prompt is refresh manually, the page_title
parameter will have underscores instead of any spaces. On the other hand
when it is invoked automatically, the page_title parameter has spaces in
it. This means that when you look at diffs in the version history of the
comparison subpage, you'll see spurious differences (spaces to
underscores) when mixing manual and automatic refreshes.
It seems more robust that the DiffOutputGenerator class normalizes the
page_title parameter to one of these forms so it's consistently dealing
with just one; I've chosen to normalize to spaces in this commit.
> Normalize underscores to spaces to avoid spurious comparison diffs

- templates/header_template.erb
- templates/row_added.erb
- templates/row_modified.erb
- templates/row_removed.erb
Rather than having a single column that attempts to show changes in values this instead splits out separate columns, one for the value in the SPARQL query and one for the value in the CSV.
This makes it more obvious where the values are coming from and how they're changing.
Fixes https://github.com/everypolitician/compare_with_wikidata/issues/80
Fixes https://github.com/everypolitician/compare_with_wikidata/issues/81
You can see this in action on this prompt comparison page:
[User:Chris_Mytton/sandbox/prompts/Pakistan_National_Assembly_EveryPolitician/comparison](https://www.wikidata.org/w/index.php?title=User:Chris_Mytton/sandbox/prompts/Pakistan_National_Assembly_EveryPolitician/comparison&oldid=571659142)
> Use separate SPARQL and CSV values in default comparison view

- lib/compare_with_wikidata.rb
- lib/compare_with_wikidata/comparison.rb
A couple of times now I've wanted to get the information out of a prompt comparison table for use with QuickStatements or similar. Copying and pasting the HTML into vim to get the Q values out works, but isn't optimal.
This change adds a `/csv` subpage to the prompt so you can retrieve the raw CSV.
You can see it in action here:
https://www.wikidata.org/wiki/User:Chris_Mytton/prompts/Argentina/Chamber_of_Deputies/csv
At the moment this doesn't render nicely in the Wikidata interface, since it's just raw CSV data, but perhaps that doesn't matter, as you can just edit the source and copy the CSV out. I'm opening this pull request to get feedback on whether this is a good idea and to see if anyone has any suggestions for improvements or alternatives.
> Write raw comparison CSV to Wikidata

- test/test_helper.rb
When working with tests, it's often useful to drop into `pry` to examine
what's going on. Pre-loading `pry` makes it easier to do that without
also remembering to `require` it in a specific test, and then remove it
again later.
This is a common pattern across lots of our repos.
> Preload 'pry' in test_helper

- test/compare_with_wikidata/comparison_test.rb
There may be edge cases or other variations on this we want to add
later, but this makes sure that we at least have _some_ coverage of the
method.
Closes #110 
I was initially a little surprised that the CSV generated in the second case had a `name` header, as the test data only uses `id`. But this is because the `subject` [defined at line 4](https://github.com/everypolitician/compare_with_wikidata/blob/c329e6493b/test/compare_with_wikidata/comparison_test.rb#L4) explicitly sets the columns for both groups of tests. I suspect that each group should really have its own `subject` defined, but changing that seems like something that should really happen in a different PR.
> Add simple tests for Comparison#to_csv

- lib/compare_with_wikidata/diff_row.rb
- lib/compare_with_wikidata/diff_row/cell.rb
Rather than creating each Cell with an already processed version of its
contents, move the logic for manipulating the contents into the Cell class
instead.
This moves the logic to where it more rightly belongs, and makes it
easier for us to handle the CellModified case (where we can have
Wikidata IDs on either "side" of the change).
> Refactoring: move processing of cell values into a new CellValue class

- README.md
- compare_with_wikidata.gemspec
- test/test_helper.rb
This adds simplecov dependency and configuration, which will allow us to see the current test coverage for the library.
Fixes #124
> Add simplecov for test coverage

- lib/compare_with_wikidata/diff_row/cell.rb
- test/compare_with_wikidata/diff_row_test.rb
There was an uncaught regression introduced when the `CellValue` class was added that meant cells with an empty string were causing an error because `nil` was being passed to the `CellValue` constructor, which causes an error because it inherits from `String`.
This change fixes that by making `CellValue` a plain class. As an added bonus this also clears up a reek warning about [inheriting from core classes](https://github.com/troessner/reek/blob/master/docs/Subclassed-From-Core-Class.md).
Fixes #127
> Fix rendering of cells with blank value

- lib/compare_with_wikidata.rb
- lib/compare_with_wikidata/mediawiki_api_client.rb
- test/compare_with_wikidata/mediawiki_api_client_test.rb
We've had a problem reported with edits made by this tool: the Prompter
Bot account, which edits are made by in the production deployment, has
a bot flag for the account, but isn't setting the bot flag on the edits it
makes:
https://www.wikidata.org/wiki/User_talk:Chris_Mytton#Bot_flag
This pull request looks at the username of the account the edit is being
made under, and will add the bot flag to edits when the username is
'Prompter Bot' (overridable with the `BOT_USERNAME` environment
variable).
This doesn't deal with refactoring the `run!` method of
`DiffOutputGenerator` or testing that the new proxy client class is used
by that method, because we've established that such refactoring (and
getting `run!` under test) is a larger task, and we should be dealing with
this user complaint as …
> Use the bot flag on edits made by the bot user

- exe/compare_with_wikidata
Ruby 2.6 is apparently going to start warning about this, and so Rubocop has introduced a check for it:
https://github.com/bbatsov/rubocop/pull/5871/files
Closes #134
> Don't splat keyword arguments as a single Hash

- lib/compare_with_wikidata/diff_row/cell.rb
- test/compare_with_wikidata/comparison_test.rb
- test/compare_with_wikidata/diff_row_test.rb
https://github.com/everypolitician/compare_with_wikidata/pull/120 introduced a subtle regression, where, when one or more cells in a row have changed (and thus the row itself is marked as 'modified', a cell that was unchanged showed up as changing to itself.
Rather than showing an id, say, changing from "2->2", we should simply show the unchanged "2" as the value.
Closes https://github.com/everypolitician/compare_with_wikidata/issues/132
Tested on live data with https://www.wikidata.org/w/index.php?title=User%3AOravrattas%2Fprompts%2FScottish_Parliament%2Fcomparison&type=revision&diff=686716807&oldid=674024357:
Before:
After:
> Don't show unchanged values changing to themselves
